### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [kub4l4/ProjectJS#1]
1. Co to jest? Proszę dodać `README.md`.
2. Używać pylinta (2. rozdział Poradnika).
3. [Importy posortować](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L5) (2. rozdział). Niepotrzebne puste wiersze powyrzucać.
4. [To](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L15) do funkcji `main()`. Na wczytywanie obrazków zastosować przepis `Assets` z 3. rozdziału (w pliku `main.py`). Ze `SCREEN` itp. zrobić zmienne lokalne w `main()`, czy raczej w `game()` lub jeszcze gdzie indziej, przekazywane do tych funkcji, które ich potrzebują.
5. [Zmienne globalne są be](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L57) (2. rozdział). Wyrzucić stąd `key`, niech `buttons()` zwraca taką parę (w krotce, już nie w liście), i niech będzie ona przekazywana tam, gdzie jest potrzebna.
6. [Poczytać o formatowaniu docstringów](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L73) (2. rozdział, TL;DR: wielkie litery i kropki).
7. [Tworzenie każdego pocisku nie powinno powodować czytania z dysku](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L132). Użyć przepisu `Assets` z punktu 4.
7. [Po co komu taka ułomna klasa](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L146)? [Ta też](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L221). Przypuszczam, że ich atrybuty spokojnie mogłyby być zmiennymi lokalnymi w głównej pętli programu.
8. [Zły styl nazw](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L151). Pylint!
9. [To](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L161) wydaje się nieużywane.
10. [Magiczne liczby zamienić na nazwane stałe](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L175) (2. rozdział). [Tu też](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L318). [Tu też](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L410) — wtedy [ten komentarz](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L448) wyrzucić.
11. [Używać f-stringów](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L250) (2. rozdział). W innych miejscach to samo.
12. [Wyrzucić](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L337).
13. [`math.hypot()`](https://github.com/kub4l4/ProjectJS/blob/be1f69a6bac4253d04df3f331bb3ddf6eb29da8f/main.py#L374).
14. Gdzie testy (3. rozdział)?

**Comment by kub4l4** [comment]
Poprawki zostały dodane. Punkt 15 doślę w następnym commit.

**Comment by MarcinCiura** [comment]
Do tego, co widzę, nie mam uwag. Czekam na testy.

**Comment by kub4l4** [comment]
Testy zostały wysłane.

**Comment by MarcinCiura** [comment]
1. [`.assertTrue()`](https://github.com/kub4l4/ProjectJS/blob/dd5456b7d40894eb2af736f2c66fb2847a7e925d/main_test.py#L52).
2. Docstringi do klas z testami są dobre dla odmóżdżonych czytelników kodu. Podpadają pod paragraf "lub w inny sposób oczywiste" z 2. rozdziału. Skasować (3. rozdział).
3. `pygame.init()` i `main.Assets.load()` lepiej przenieść albo do `setUpClass()`, żeby się rzadziej robiły, albo wręcz na sam dół, pod `if`-em, a nad `unittest.main()`.

**Comment by kub4l4** [comment]
Dostałem prośbę o przekazanie Panu doktorowi adresu do projektu jednego ze studentów:
https://github.com/Szymon981/JS

**Comment by kub4l4** [comment]
Testy zostały poprawione, wszystkie dają wynik OK. Po wprowadzeniu `pygame.init()` i `main.Assets.load()` do `if`a testy się nie komplikowały i pojawiały się błędy przy klasie `BulletTest`. Po wprowadzeniu `pygame.init()` i `main.Assets.load()` tylko do tej klasy wszystko działa prawidłowo.

**Comment by MarcinCiura** [comment]
1. Nalegam na użycie `setUpClass()`, ponieważ `main.Assets.load()` to dość pokaźna operacja, związana z czytaniem plików z dysku, i głupio by było ją robić przed każdym testem jednostkowym, gdyby kiedyś powstało ich więcej.
2. Dziwne, jestem przekonany, że dzisiaj pisałem uwagi na temat dzieła pana kolegi. Widocznie się nie zapisały; napiszę jeszcze raz.

**Comment by kub4l4** [comment]
`setUpClass()` została dodana.

**Comment by MarcinCiura** [comment]
Dziękuję za zmianę. Jeszcze parę uwag i będzie po wszystkim.
1. [Niepotrzebne](https://github.com/kub4l4/ProjectJS/blob/840cda75244d971edcd6e2146eaa2a1a578a7622/main_test.py#L39). Pisać `self.assertTrue(spam(23, 45, 65, 33, 99))`.
2. Miejsce [tego](https://github.com/kub4l4/ProjectJS/blob/840cda75244d971edcd6e2146eaa2a1a578a7622/main_test.py#L53) też nie jest w `setUp()`. Przenieść do metody. [Tu](https://github.com/kub4l4/ProjectJS/blob/840cda75244d971edcd6e2146eaa2a1a578a7622/main_test.py#L61) też.

**Comment by kub4l4** [comment]
Poprawione. Dużo lepiej to teraz wygląda.

**Comment by MarcinCiura** [comment]
LGTM
